name: Kaggle GPU Runner

on:
  workflow_dispatch:

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push Kernel
        uses: Frederisk/kaggle-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          id: junioronl/gpu_runner_test
          title: gpu_runner_test
          code_file: .github/script/gpu_runner.py
          language: python
          kernel_type: script
          enable_gpu: true
          enable_internet: true
